apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: momo-store
  labels:
    app: frontend
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: frontend
              containerPort: {{ .Values.appContainerPort }}
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d
            - name: docker-socket
              mountPath: /tmp/docker.sock
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config-frontend
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
      imagePullSecrets:
        - name: docker-config-secret
