stages:
  - module-pipelines

frontend-job:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
    - frontend/**/*

backend-job:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - backend/**/*

helm-job:
  stage: module-pipelines
  trigger:
    include:
      - "/helm-momo-store-chart/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - infrastructure/helm-momo-store-chart/**/*
