stages:
  - module-pipelines

frontend-job:
  stage: module-pipelines
  trigger:
    include:
      - "application//frontend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
    - application/frontend/**/*

backend-job:
  stage: module-pipelines
  trigger:
    include:
      - "application//backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - application/backend/**/*

helm-job:
  stage: module-pipelines
  trigger:
    include:
      - "infrastructure/helm-momo-store-chart/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - infrastructure/helm-momo-store-chart/**/*
