apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: momo-store
  name: argocd-namespace-manager-binding
subjects:
- kind: ServiceAccount
  name: momo # Имя учетной записи сервиса ArgoCD
  namespace: argocd # Пространство имен, где запущен ArgoCD
roleRef:
  kind: Role
  name: argocd-namespace-manager
  apiGroup: rbac.authorization.k8s.io
