apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: momo-store
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: backend
          containerPort: {{ .Values.containerPort }}
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config-backend
      imagePullSecrets:
      - name: docker-config-secret
