apiVersion: v1
kind: Service
metadata:
  namespace: momo-store
  name: backend
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.serviceContainerPort }}
      protocol: TCP
      targetPort: {{ .Values.serviceContainerTargerPort }}
  selector:
    app: backend
