stages:
  - build
  - test
  - release

include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  SONAR_PROJECT_NAME: store_backend

build-backend:
  stage: build
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd application/backend
    - >
      docker build
      --build-arg VERSION=$VERSION
      --tag $CI_REGISTRY_IMAGE/store-backend:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE/store-backend:$CI_COMMIT_SHA
  rules:
    - when: manual

sonarqube-backend-sast:
  variables:
    compile: "true"
  stage: test
  only:
    changes:
      - backend/*
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner
      -Dsonar.sources=application/backend
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACKEND}
      -Dsonar.host.url=${SONARQUBE_URL_BACKEND}
      -Dsonar.login=${SONAR_LOGIN_BACKEND}
      -Dsonar.projectName=${SONAR_PROJECT_NAME}
  needs:
    - build-backend

gitlab-sast:
  stage: test
  needs:
    - build-backend
  trigger:
    include:
      - template: Security/SAST.gitlab-ci.yml

upload-backend-latest:
  stage: release
  variables:
    GIT_STRATEGY: none
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/store-backend:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/store-backend:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/store-backend:latest
    - docker push $CI_REGISTRY_IMAGE/store-backend:latest
